stages:
  - build
  - test
  - deploy

maven-build:
  image: maven:3.8.1-jdk-11-slim
  stage: build
  script: "mvn clean package"
  only:
    - master

maven-test:
  image: maven:3.8.1-jdk-11-slim
  stage: test
  script: "mvn clean test"
  only:
    - master

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=ttc-book-meeting-room-backend --api-key=$HEROKU_API_KEY
  only:
    - master